version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - davidB
  ignore:
  - dependency-name: nalgebra
    versions:
    - 0.24.0
    - 0.25.0
    - 0.26.1
  - dependency-name: derive_builder
    versions:
    - 0.10.0
  - dependency-name: ndarray-rand
    versions:
    - 0.13.0
