[package]
name = "vega_lite_3"
version = "0.1.1-dev"
authors = ["David Bernard <david.bernard.31@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "rust api for vega-lite v3"
repository = "https://github.com/davidB/showata"
readme = "README.md"
#category = ["visualization"]
keywords = ["visualization", "plot", "vega"]

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.39"
derive_builder = "0.9.0"
#showata = {version = "0.1.0-dev", optional = true, path = "../showata"}
showata = {version = "0.1.0", optional = true}
failure = {version = "0.1.5", optional = true }

[dev-dependencies]
csv = "1.0"

[features]
show_vega = ["showata", "failure"]

[[example]]
name = "scatterplot"
required-features = ["show_vega"]

[[example]]
name = "stock_graph"
required-features = ["show_vega"]
